#!/usr/bin/env node
// GENERATED by scripts/build-cli.ts from packages/cli/src/cli/ — do not edit. Run `bun run build` in packages/cli.

// ../../node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
import { basename } from "node:path";

// ../../node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/errors.js
var AxiError = class extends Error {
  code;
  suggestions;
  constructor(message, code, suggestions = []) {
    super(message);
    this.code = code;
    this.suggestions = suggestions;
    this.name = "AxiError";
  }
};
function exitCodeForError(error) {
  if (error instanceof AxiError && error.code === "VALIDATION_ERROR") {
    return 2;
  }
  return 1;
}

// ../../node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
import { homedir } from "node:os";

// ../../node_modules/.bun/@toon-format+toon@2.3.0/node_modules/@toon-format/toon/dist/index.mjs
var NULL_LITERAL = "null";
var DELIMITERS = {
  comma: ",",
  tab: "	",
  pipe: "|"
};
var DEFAULT_DELIMITER = DELIMITERS.comma;
function escapeString(value) {
  return value.replace(/\\/g, `\\\\`).replace(/"/g, `\\"`).replace(/\n/g, `\\n`).replace(/\r/g, `\\r`).replace(/\t/g, `\\t`).replace(/[\u0000-\u001F]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}
function isBooleanOrNullLiteral(token) {
  return token === "true" || token === "false" || token === "null";
}
function normalizeValue(value) {
  if (value === null) return null;
  if (typeof value === "object" && value !== null && "toJSON" in value && typeof value.toJSON === "function") {
    const next = value.toJSON();
    if (next !== value) return normalizeValue(next);
  }
  if (typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (Object.is(value, -0)) return 0;
    if (!Number.isFinite(value)) return null;
    return value;
  }
  if (typeof value === "bigint") {
    if (value >= Number.MIN_SAFE_INTEGER && value <= Number.MAX_SAFE_INTEGER) return Number(value);
    return value.toString();
  }
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value instanceof Set) return Array.from(value).map(normalizeValue);
  if (value instanceof Map) return Object.fromEntries(Array.from(value, ([k, v]) => [String(k), normalizeValue(v)]));
  if (isPlainObject(value)) {
    const encodedValues = {};
    for (const key in value) if (Object.hasOwn(value, key)) encodedValues[key] = normalizeValue(value[key]);
    return encodedValues;
  }
  return null;
}
function isJsonPrimitive(value) {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}
function isJsonArray(value) {
  return Array.isArray(value);
}
function isJsonObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
function isEmptyObject(value) {
  return Object.keys(value).length === 0;
}
function isPlainObject(value) {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === null || prototype === Object.prototype;
}
function isArrayOfPrimitives(value) {
  return value.length === 0 || value.every((item) => isJsonPrimitive(item));
}
function isArrayOfArrays(value) {
  return value.length === 0 || value.every((item) => isJsonArray(item));
}
function isArrayOfObjects(value) {
  return value.length === 0 || value.every((item) => isJsonObject(item));
}
var NUMERIC_LIKE_PATTERN = /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i;
var LEADING_ZERO_PATTERN = /^0\d+$/;
function isValidUnquotedKey(key) {
  return /^[A-Z_][\w.]*$/i.test(key);
}
function isIdentifierSegment(key) {
  return /^[A-Z_]\w*$/i.test(key);
}
function isSafeUnquoted(value, delimiter = DEFAULT_DELIMITER) {
  if (!value) return false;
  if (value !== value.trim()) return false;
  if (isBooleanOrNullLiteral(value) || isNumericLike(value)) return false;
  if (value.includes(":")) return false;
  if (value.includes('"') || value.includes("\\")) return false;
  if (/[[\]{}]/.test(value)) return false;
  if (/[\u0000-\u001F]/.test(value)) return false;
  if (value.includes(delimiter)) return false;
  if (value.startsWith("-")) return false;
  return true;
}
function isNumericLike(value) {
  return NUMERIC_LIKE_PATTERN.test(value) || LEADING_ZERO_PATTERN.test(value);
}
function tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, flattenDepth) {
  if (options.keyFolding !== "safe") return;
  if (!isJsonObject(value)) return;
  const { segments, tail, leafValue } = collectSingleKeyChain(key, value, flattenDepth ?? options.flattenDepth);
  if (segments.length < 2) return;
  if (!segments.every((seg) => isIdentifierSegment(seg))) return;
  const foldedKey = buildFoldedKey(segments);
  const absolutePath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
  if (siblings.includes(foldedKey)) return;
  if (rootLiteralKeys && rootLiteralKeys.has(absolutePath)) return;
  return {
    foldedKey,
    remainder: tail,
    leafValue,
    segmentCount: segments.length
  };
}
function collectSingleKeyChain(startKey, startValue, maxDepth) {
  const segments = [startKey];
  let currentValue = startValue;
  while (segments.length < maxDepth) {
    if (!isJsonObject(currentValue)) break;
    const keys = Object.keys(currentValue);
    if (keys.length !== 1) break;
    const nextKey = keys[0];
    const nextValue = currentValue[nextKey];
    segments.push(nextKey);
    currentValue = nextValue;
  }
  if (!isJsonObject(currentValue) || isEmptyObject(currentValue)) return {
    segments,
    tail: void 0,
    leafValue: currentValue
  };
  return {
    segments,
    tail: currentValue,
    leafValue: currentValue
  };
}
function buildFoldedKey(segments) {
  return segments.join(".");
}
function encodePrimitive(value, delimiter) {
  if (value === null) return NULL_LITERAL;
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  return encodeStringLiteral(value, delimiter);
}
function encodeStringLiteral(value, delimiter = DEFAULT_DELIMITER) {
  if (isSafeUnquoted(value, delimiter)) return value;
  return `"${escapeString(value)}"`;
}
function encodeKey(key) {
  if (isValidUnquotedKey(key)) return key;
  return `"${escapeString(key)}"`;
}
function encodeAndJoinPrimitives(values, delimiter = DEFAULT_DELIMITER) {
  return values.map((v) => encodePrimitive(v, delimiter)).join(delimiter);
}
function formatHeader(length, options) {
  const key = options?.key;
  const fields = options?.fields;
  const delimiter = options?.delimiter ?? ",";
  let header = "";
  if (key != null) header += encodeKey(key);
  header += `[${length}${delimiter !== DEFAULT_DELIMITER ? delimiter : ""}]`;
  if (fields) {
    const quotedFields = fields.map((f) => encodeKey(f));
    header += `{${quotedFields.join(delimiter)}}`;
  }
  header += ":";
  return header;
}
function* encodeJsonValue(value, options, depth) {
  if (isJsonPrimitive(value)) {
    const encodedPrimitive = encodePrimitive(value, options.delimiter);
    if (encodedPrimitive !== "") yield encodedPrimitive;
    return;
  }
  if (isJsonArray(value)) yield* encodeArrayLines(void 0, value, depth, options);
  else if (isJsonObject(value)) yield* encodeObjectLines(value, depth, options);
}
function* encodeObjectLines(value, depth, options, rootLiteralKeys, pathPrefix, remainingDepth) {
  const keys = Object.keys(value);
  if (depth === 0 && !rootLiteralKeys) rootLiteralKeys = new Set(keys.filter((k) => k.includes(".")));
  const effectiveFlattenDepth = remainingDepth ?? options.flattenDepth;
  for (const [key, val] of Object.entries(value)) yield* encodeKeyValuePairLines(key, val, depth, options, keys, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
}
function* encodeKeyValuePairLines(key, value, depth, options, siblings, rootLiteralKeys, pathPrefix, flattenDepth) {
  const currentPath = pathPrefix ? `${pathPrefix}.${key}` : key;
  const effectiveFlattenDepth = flattenDepth ?? options.flattenDepth;
  if (options.keyFolding === "safe" && siblings) {
    const foldResult = tryFoldKeyChain(key, value, siblings, options, rootLiteralKeys, pathPrefix, effectiveFlattenDepth);
    if (foldResult) {
      const { foldedKey, remainder, leafValue, segmentCount } = foldResult;
      const encodedFoldedKey = encodeKey(foldedKey);
      if (remainder === void 0) {
        if (isJsonPrimitive(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}: ${encodePrimitive(leafValue, options.delimiter)}`, options.indent);
          return;
        } else if (isJsonArray(leafValue)) {
          yield* encodeArrayLines(foldedKey, leafValue, depth, options);
          return;
        } else if (isJsonObject(leafValue) && isEmptyObject(leafValue)) {
          yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
          return;
        }
      }
      if (isJsonObject(remainder)) {
        yield indentedLine(depth, `${encodedFoldedKey}:`, options.indent);
        const remainingDepth = effectiveFlattenDepth - segmentCount;
        const foldedPath = pathPrefix ? `${pathPrefix}.${foldedKey}` : foldedKey;
        yield* encodeObjectLines(remainder, depth + 1, options, rootLiteralKeys, foldedPath, remainingDepth);
        return;
      }
    }
  }
  const encodedKey = encodeKey(key);
  if (isJsonPrimitive(value)) yield indentedLine(depth, `${encodedKey}: ${encodePrimitive(value, options.delimiter)}`, options.indent);
  else if (isJsonArray(value)) yield* encodeArrayLines(key, value, depth, options);
  else if (isJsonObject(value)) {
    yield indentedLine(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(value)) yield* encodeObjectLines(value, depth + 1, options, rootLiteralKeys, currentPath, effectiveFlattenDepth);
  }
}
function* encodeArrayLines(key, value, depth, options) {
  if (value.length === 0) {
    yield indentedLine(depth, key != null ? `${encodeKey(key)}: []` : "[]", options.indent);
    return;
  }
  if (isArrayOfPrimitives(value)) {
    yield indentedLine(depth, encodeInlineArrayLine(value, options.delimiter, key), options.indent);
    return;
  }
  if (isArrayOfArrays(value)) {
    if (value.every((arr) => isArrayOfPrimitives(arr))) {
      yield* encodeArrayOfArraysAsListItemsLines(key, value, depth, options);
      return;
    }
  }
  if (isArrayOfObjects(value)) {
    const header = extractTabularHeader(value);
    if (header) yield* encodeArrayOfObjectsAsTabularLines(key, value, header, depth, options);
    else yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
    return;
  }
  yield* encodeMixedArrayAsListItemsLines(key, value, depth, options);
}
function* encodeArrayOfArraysAsListItemsLines(prefix, values, depth, options) {
  yield indentedLine(depth, formatHeader(values.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const arr of values) if (isArrayOfPrimitives(arr)) {
    const arrayLine = encodeInlineArrayLine(arr, options.delimiter);
    yield indentedListItem(depth + 1, arrayLine, options.indent);
  }
}
function encodeInlineArrayLine(values, delimiter, prefix) {
  const header = formatHeader(values.length, {
    key: prefix,
    delimiter
  });
  const joinedValue = encodeAndJoinPrimitives(values, delimiter);
  if (values.length === 0) return header;
  return `${header} ${joinedValue}`;
}
function* encodeArrayOfObjectsAsTabularLines(prefix, rows, header, depth, options) {
  yield indentedLine(depth, formatHeader(rows.length, {
    key: prefix,
    fields: header,
    delimiter: options.delimiter
  }), options.indent);
  yield* writeTabularRowsLines(rows, header, depth + 1, options);
}
function extractTabularHeader(rows) {
  if (rows.length === 0) return;
  const firstRow = rows[0];
  const firstKeys = Object.keys(firstRow);
  if (firstKeys.length === 0) return;
  if (isTabularArray(rows, firstKeys)) return firstKeys;
}
function isTabularArray(rows, header) {
  for (const row of rows) {
    if (Object.keys(row).length !== header.length) return false;
    for (const key of header) {
      if (!(key in row)) return false;
      if (!isJsonPrimitive(row[key])) return false;
    }
  }
  return true;
}
function* writeTabularRowsLines(rows, header, depth, options) {
  for (const row of rows) yield indentedLine(depth, encodeAndJoinPrimitives(header.map((key) => row[key]), options.delimiter), options.indent);
}
function* encodeMixedArrayAsListItemsLines(prefix, items, depth, options) {
  yield indentedLine(depth, formatHeader(items.length, {
    key: prefix,
    delimiter: options.delimiter
  }), options.indent);
  for (const item of items) yield* encodeListItemValueLines(item, depth + 1, options);
}
function* encodeObjectAsListItemLines(obj, depth, options) {
  if (isEmptyObject(obj)) {
    yield indentedLine(depth, "-", options.indent);
    return;
  }
  const entries = Object.entries(obj);
  const [firstKey, firstValue] = entries[0];
  const restEntries = entries.slice(1);
  if (isJsonArray(firstValue) && isArrayOfObjects(firstValue)) {
    const header = extractTabularHeader(firstValue);
    if (header) {
      yield indentedListItem(depth, formatHeader(firstValue.length, {
        key: firstKey,
        fields: header,
        delimiter: options.delimiter
      }), options.indent);
      yield* writeTabularRowsLines(firstValue, header, depth + 2, options);
      if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
      return;
    }
  }
  const encodedKey = encodeKey(firstKey);
  if (isJsonPrimitive(firstValue)) yield indentedListItem(depth, `${encodedKey}: ${encodePrimitive(firstValue, options.delimiter)}`, options.indent);
  else if (isJsonArray(firstValue)) if (firstValue.length === 0) yield indentedListItem(depth, `${encodedKey}: []`, options.indent);
  else if (isArrayOfPrimitives(firstValue)) yield indentedListItem(depth, `${encodedKey}${encodeInlineArrayLine(firstValue, options.delimiter)}`, options.indent);
  else {
    yield indentedListItem(depth, `${encodedKey}${formatHeader(firstValue.length, { delimiter: options.delimiter })}`, options.indent);
    for (const item of firstValue) yield* encodeListItemValueLines(item, depth + 2, options);
  }
  else if (isJsonObject(firstValue)) {
    yield indentedListItem(depth, `${encodedKey}:`, options.indent);
    if (!isEmptyObject(firstValue)) yield* encodeObjectLines(firstValue, depth + 2, options);
  }
  if (restEntries.length > 0) yield* encodeObjectLines(Object.fromEntries(restEntries), depth + 1, options);
}
function* encodeListItemValueLines(value, depth, options) {
  if (isJsonPrimitive(value)) yield indentedListItem(depth, encodePrimitive(value, options.delimiter), options.indent);
  else if (isJsonArray(value)) if (isArrayOfPrimitives(value)) yield indentedListItem(depth, encodeInlineArrayLine(value, options.delimiter), options.indent);
  else {
    yield indentedListItem(depth, formatHeader(value.length, { delimiter: options.delimiter }), options.indent);
    for (const item of value) yield* encodeListItemValueLines(item, depth + 1, options);
  }
  else if (isJsonObject(value)) yield* encodeObjectAsListItemLines(value, depth, options);
}
function indentedLine(depth, content, indentSize) {
  return " ".repeat(indentSize * depth) + content;
}
function indentedListItem(depth, content, indentSize) {
  return indentedLine(depth, "- " + content, indentSize);
}
function applyReplacer(root, replacer) {
  const replacedRoot = replacer("", root, []);
  if (replacedRoot === void 0) return transformChildren(root, replacer, []);
  return transformChildren(normalizeValue(replacedRoot), replacer, []);
}
function transformChildren(value, replacer, path) {
  if (isJsonObject(value)) return transformObject(value, replacer, path);
  if (isJsonArray(value)) return transformArray(value, replacer, path);
  return value;
}
function transformObject(obj, replacer, path) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const childPath = [...path, key];
    const replacedValue = replacer(key, value, childPath);
    if (replacedValue === void 0) continue;
    result[key] = transformChildren(normalizeValue(replacedValue), replacer, childPath);
  }
  return result;
}
function transformArray(arr, replacer, path) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    const value = arr[i];
    const childPath = [...path, i];
    const replacedValue = replacer(String(i), value, childPath);
    if (replacedValue === void 0) continue;
    const normalizedValue = normalizeValue(replacedValue);
    result.push(transformChildren(normalizedValue, replacer, childPath));
  }
  return result;
}
function encode(input, options) {
  return Array.from(encodeLines(input, options)).join("\n");
}
function encodeLines(input, options) {
  const normalizedValue = normalizeValue(input);
  const resolvedOptions = resolveOptions(options);
  return encodeJsonValue(resolvedOptions.replacer ? applyReplacer(normalizedValue, resolvedOptions.replacer) : normalizedValue, resolvedOptions, 0);
}
function resolveOptions(options) {
  return {
    indent: options?.indent ?? 2,
    delimiter: options?.delimiter ?? DEFAULT_DELIMITER,
    keyFolding: options?.keyFolding ?? "off",
    flattenDepth: options?.flattenDepth ?? Number.POSITIVE_INFINITY,
    replacer: options?.replacer
  };
}

// ../../node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/output.js
function collapseHomeDirectory(path, homeDir = homedir()) {
  if (!path.startsWith(homeDir)) {
    return path;
  }
  return `~${path.slice(homeDir.length)}`;
}
function homeHeaderOutput(options) {
  return {
    bin: collapseHomeDirectory(options.execPath ?? process.argv[1] ?? "", options.homeDir),
    description: options.description
  };
}
function errorOutput(message, code, suggestions = []) {
  const output = {
    error: message,
    code
  };
  if (suggestions.length > 0) {
    output.help = suggestions;
  }
  return output;
}
function renderOutput(output) {
  if (typeof output === "string") {
    return output;
  }
  return encode(output);
}
function renderError(message, code, suggestions = []) {
  return renderOutput(errorOutput(message, code, suggestions));
}

// ../../node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/cli.js
function defaultFormatError(error) {
  if (error instanceof AxiError) {
    return {
      output: `${renderError(error.message, error.code, error.suggestions)}
`,
      exitCode: exitCodeForError(error)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderError(message, "UNKNOWN")}
`,
    exitCode: 1
  };
}
function defaultUnknownCommand(command) {
  return `${renderError(`Unknown command: ${command}`, "VALIDATION_ERROR", [
    "Run `--help` to see available commands"
  ])}
`;
}
async function runAxiCli(options) {
  options.initialize?.();
  const stdout = options.stdout ?? process.stdout;
  const argv = options.argv ?? process.argv.slice(2);
  if (argv.length === 1 && argv[0] === "--help") {
    stdout.write(options.topLevelHelp);
    return;
  }
  if (argv.length === 1 && isVersionFlag(argv[0])) {
    if (!options.version) {
      stdout.write(`${renderError("Version is not configured for this tool", "VALIDATION_ERROR")}
`);
      process.exitCode = 2;
      return;
    }
    stdout.write(`${options.version}
`);
    return;
  }
  const command = argv[0];
  if (!command) {
    const context2 = await options.resolveContext?.({
      command: void 0,
      args: []
    });
    await runHandler(options.home, [], context2, stdout, options, true);
    return;
  }
  if (command.startsWith("-")) {
    stdout.write(renderLeadingFlagError(command));
    process.exitCode = 2;
    return;
  }
  const args = argv.slice(1);
  if (args.includes("--help")) {
    const help = options.getCommandHelp?.(command);
    if (help) {
      stdout.write(help);
      return;
    }
  }
  const handler = options.commands[command];
  if (!handler) {
    stdout.write((options.renderUnknownCommand ?? defaultUnknownCommand)(command));
    process.exitCode = 2;
    return;
  }
  const context = await options.resolveContext?.({ command, args });
  await runHandler(handler, args, context, stdout, options, false);
}
async function runHandler(handler, args, context, stdout, options, isHomeView) {
  try {
    const output = await handler(args, context);
    stdout.write(`${renderCommandOutput(output, options, isHomeView)}
`);
  } catch (error) {
    const formatted = (options.formatError ?? defaultFormatError)(error);
    stdout.write(formatted.output);
    process.exitCode = formatted.exitCode;
  }
}
function renderLeadingFlagError(flag) {
  const bin = basename(process.argv[1] ?? "tool") || "tool";
  return `${renderError("Flags must come after the command", "VALIDATION_ERROR", [
    `Run \`${bin} <command> [args] [flags]\``,
    `Move \`${flag}\` after the command instead of before it`
  ])}
`;
}
function isVersionFlag(flag) {
  return flag === "-v" || flag === "-V" || flag === "--version";
}
function renderCommandOutput(output, options, isHomeView) {
  if (!isHomeView) {
    return renderOutput(output);
  }
  const header = homeHeaderOutput({ description: options.description });
  if (typeof output === "string") {
    return `${renderOutput(header)}
${output}`;
  }
  return renderOutput(mergeHomeHeader(header, output));
}
function mergeHomeHeader(header, output) {
  const rest = { ...output };
  delete rest.bin;
  delete rest.description;
  return {
    ...header,
    ...rest
  };
}

// ../../node_modules/.bun/axi-sdk-js@0.1.7/node_modules/axi-sdk-js/dist/hooks.js
function isManagedHook(hook, marker) {
  return typeof hook?.command === "string" && hook.command.includes(marker);
}
function computeSessionStartHookUpdate(settings, spec) {
  const updated = structuredClone(settings);
  let changed = false;
  if (!updated.hooks) {
    updated.hooks = {};
    changed = true;
  }
  if (Array.isArray(updated.hooks.session_start)) {
    const legacyHooks = updated.hooks.session_start.filter((hook) => !isManagedHook(hook, spec.marker));
    if (legacyHooks.length !== updated.hooks.session_start.length) {
      changed = true;
      if (legacyHooks.length === 0) {
        delete updated.hooks.session_start;
      } else {
        updated.hooks.session_start = legacyHooks;
      }
    }
  }
  if (!Array.isArray(updated.hooks.SessionStart)) {
    updated.hooks.SessionStart = [];
    changed = true;
  }
  for (const group of updated.hooks.SessionStart) {
    if (!Array.isArray(group.hooks)) {
      continue;
    }
    for (const hook of group.hooks) {
      if (!isManagedHook(hook, spec.marker)) {
        continue;
      }
      const timeout = spec.timeoutSeconds ?? 10;
      const isCorrect = hook.command === spec.command && hook.type === "command" && hook.timeout === timeout;
      if (isCorrect && !changed) {
        return [settings, false];
      }
      hook.command = spec.command;
      hook.type = "command";
      hook.timeout = timeout;
      return [updated, true];
    }
  }
  updated.hooks.SessionStart.push({
    matcher: "",
    hooks: [
      {
        type: "command",
        command: spec.command,
        timeout: spec.timeoutSeconds ?? 10
      }
    ]
  });
  return [updated, true];
}

// src/cli/flags.ts
var ALWAYS_ALLOWED = /* @__PURE__ */ new Set(["--help", "-h"]);
var GLOBAL_VALUE_FLAGS = /* @__PURE__ */ new Set(["--actor", "--profile"]);
var GLOBAL_BOOLEAN_FLAGS = /* @__PURE__ */ new Set(["--json"]);
function isValueLike(arg) {
  if (arg === void 0) return false;
  if (!arg.startsWith("-")) return true;
  return /^-[.\d]/.test(arg);
}
function parseFlags(command, argv, spec) {
  const valueFlags = new Set(spec.value ?? []);
  const boolFlags = new Set(spec.boolean ?? []);
  const deprecated = spec.deprecated ?? {};
  const known = [...valueFlags, ...boolFlags].sort();
  const positional = [];
  const flags = {};
  const unknown = (name) => {
    const hint = deprecated[name];
    throw new AxiError(`unknown flag ${name} for \`${command}\``, "UNKNOWN_FLAG", [
      ...hint ? [hint] : [],
      known.length > 0 ? `valid flags for \`${command}\`: ${known.join(", ")} (--help, --actor, --json, --profile always allowed)` : `\`${command}\` takes no flags of its own (--help, --actor, --json, --profile always allowed)`
    ]);
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--") {
      positional.push(...argv.slice(i + 1));
      break;
    }
    if (!arg.startsWith("-") || arg === "-") {
      positional.push(arg);
      continue;
    }
    if (ALWAYS_ALLOWED.has(arg)) {
      flags["--help"] = true;
      continue;
    }
    const eq = arg.indexOf("=");
    const name = eq === -1 ? arg : arg.slice(0, eq);
    const inlineValue = eq === -1 ? void 0 : arg.slice(eq + 1);
    if (boolFlags.has(name) || GLOBAL_BOOLEAN_FLAGS.has(name)) {
      if (inlineValue !== void 0) {
        throw new AxiError(`${name} is a switch and takes no value`, "USAGE", [
          `Run \`drafter-axi ${command} ${name}\` without a value`
        ]);
      }
      flags[name] = true;
      continue;
    }
    if (valueFlags.has(name) || GLOBAL_VALUE_FLAGS.has(name)) {
      if (inlineValue !== void 0) {
        flags[name] = inlineValue;
        continue;
      }
      const next = argv[i + 1];
      if (!isValueLike(next)) {
        throw new AxiError(`${name} requires a value`, "USAGE", [
          `Run \`drafter-axi ${command} ${name} <value>\``
        ]);
      }
      flags[name] = next;
      i++;
      continue;
    }
    unknown(name);
  }
  const allowed = spec.positionals;
  if (allowed !== void 0 && positional.length > allowed) {
    throw new AxiError(
      allowed === 0 ? `\`${command}\` takes no positional arguments, but got "${positional[0]}"` : `\`${command}\` takes at most ${allowed} positional argument${allowed === 1 ? "" : "s"}, but got ${positional.length}`,
      "USAGE",
      [`Run \`drafter-axi ${command} --help\` for the expected form`]
    );
  }
  return { positional, flags };
}
function str(parsed, name, fallback) {
  const raw = parsed.flags[name];
  return typeof raw === "string" ? raw : fallback;
}
function bool(parsed, name) {
  return parsed.flags[name] !== void 0;
}
function csv(value) {
  if (!value) return [];
  return value.split(",").map((v) => v.trim()).filter((v) => v.length > 0);
}
function requirePositional(parsed, index, label, usage) {
  const value = parsed.positional[index];
  if (value === void 0 || value.length === 0) {
    throw new AxiError(`${label} is required`, "USAGE", [usage]);
  }
  return value;
}
function requireStr(parsed, name, usage) {
  const value = str(parsed, name);
  if (value === void 0 || value.length === 0) {
    throw new AxiError(`${name} is required`, "USAGE", [usage]);
  }
  return value;
}
function parseSubcommand(command, args, specs) {
  const first = args[0];
  if (first === void 0 || !(first in specs)) {
    throw new AxiError(
      first === void 0 ? `\`${command}\` requires a subcommand` : `unknown ${command} subcommand "${first}"`,
      "VALIDATION_ERROR",
      [`valid subcommands: ${Object.keys(specs).join(", ")}`]
    );
  }
  const parsed = parseFlags(`${command} ${first}`, args.slice(1), specs[first]);
  return { sub: first, parsed };
}

// src/cli/invocation.ts
import { accessSync, constants } from "node:fs";
import { homedir as homedir2 } from "node:os";
import { fileURLToPath } from "node:url";
var cached;
function cliInvocation() {
  if (cached) return cached;
  let bundle;
  try {
    bundle = fileURLToPath(import.meta.url);
  } catch {
    bundle = process.argv[1] ?? "drafter-axi";
  }
  const shim = bundle.replace(/\.mjs$/, "");
  try {
    if (shim !== bundle) {
      accessSync(shim, constants.X_OK);
      cached = quote(collapseHome(shim));
      return cached;
    }
  } catch {
  }
  cached = `node ${quote(collapseHome(bundle))}`;
  return cached;
}
function collapseHome(p) {
  const home = homedir2();
  return home && p.startsWith(`${home}/`) ? `~${p.slice(home.length)}` : p;
}
function quote(p) {
  return /\s/.test(p) ? `"${p}"` : p;
}

// src/cli/output.ts
function computed(name, fn) {
  return { name, extract: fn };
}
function renderList(name, items, schema) {
  const projected = items.map(
    (item) => Object.fromEntries(schema.map((f) => [f.name, f.extract(item) ?? ""]))
  );
  return encode({ [name]: projected });
}
function renderObject(value) {
  return encode(value);
}
function compact(obj) {
  return Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== void 0));
}
function renderHelp(suggestions) {
  if (suggestions.length === 0) return "";
  return `help[${suggestions.length}]:
${suggestions.map((s) => `  ${s}`).join("\n")}`;
}
function joinBlocks(...blocks) {
  return blocks.filter((b) => b.length > 0).join("\n");
}
function renderJson(value) {
  return JSON.stringify(value, null, 2);
}

// src/cli/commands/common.ts
import { readFileSync as readFileSync2 } from "node:fs";

// src/cli/errors.ts
var ApiCallError = class extends AxiError {
  details;
  constructor(apiCode, message, details = {}) {
    super(message, apiCode, []);
    this.details = details;
  }
};
var NetworkError = class extends AxiError {
  constructor(message) {
    super(message, "NETWORK_ERROR", ["Check DRAFTER_URL and that the API is reachable"]);
  }
};
var EXIT_CODE_BY_CODE = {
  // CLI-level usage errors (thrown by flags.ts / config.ts).
  USAGE: 2,
  UNKNOWN_FLAG: 2,
  VALIDATION_ERROR: 2,
  // API validation-shaped errors (400/422).
  invalid_request: 2,
  validation_failed: 2,
  invalid_anchor: 2,
  judgement_requires_comments: 2,
  attestation_required: 2,
  // API phase/conflict errors (409).
  phase_closed: 3,
  version_stale: 3,
  deadline_not_later: 3,
  stale_edit: 3,
  unsaved_items: 3,
  no_change: 3,
  no_version: 3,
  // Not found (404).
  not_found: 4,
  // Auth (401/403).
  unauthenticated: 5,
  forbidden: 5,
  csrf_required: 5,
  // Everything else (rate limits, internal errors, network failures).
  rate_limited: 1,
  internal_error: 1,
  NETWORK_ERROR: 1
};
function exitCodeForCode(code) {
  return EXIT_CODE_BY_CODE[code] ?? 1;
}

// src/cli/client.ts
var DrafterClient = class {
  constructor(config) {
    this.config = config;
  }
  config;
  async request(method, path, options = {}) {
    const url = new URL(`${this.config.url}/admin/api${path}`);
    for (const [key, value] of Object.entries(options.query ?? {})) {
      if (value !== void 0) url.searchParams.set(key, value);
    }
    const headers = {
      authorization: `Bearer ${this.config.adminToken}`,
      "x-actor": this.config.actor
    };
    let body;
    if (options.raw) {
      body = options.raw.text;
      headers["content-type"] = options.raw.contentType;
    } else if (options.body !== void 0) {
      body = JSON.stringify(options.body);
      headers["content-type"] = "application/json; charset=utf-8";
    }
    let response;
    try {
      response = await fetch(url, { method, headers, body });
    } catch (error) {
      throw new NetworkError(
        `could not reach ${this.config.url}: ${error instanceof Error ? error.message : String(error)}`
      );
    }
    const contentType = response.headers.get("content-type") ?? "";
    if (!response.ok) {
      if (contentType.includes("application/json")) {
        const payload = await response.json();
        throw new ApiCallError(payload.error, payload.message, payload.details ?? {});
      }
      const text = await response.text();
      throw new ApiCallError("internal_error", text || `HTTP ${response.status}`);
    }
    if (response.status === 204) return void 0;
    if (contentType.includes("text/csv") || contentType.includes("text/markdown")) {
      return await response.text();
    }
    if (contentType.includes("application/json")) {
      return await response.json();
    }
    return await response.text();
  }
  get(path, query) {
    return this.request("GET", path, { query });
  }
  post(path, body) {
    return this.request("POST", path, { body });
  }
  /** POST with a pre-serialized text body (NDJSON import) instead of a JSON-encoded object. */
  postText(path, text, contentType) {
    return this.request("POST", path, { raw: { text, contentType } });
  }
  patch(path, body) {
    return this.request("PATCH", path, { body });
  }
};

// src/cli/config.ts
import { existsSync, readFileSync } from "node:fs";
import { homedir as homedir3, userInfo } from "node:os";
import { join } from "node:path";
function configDir() {
  return join(homedir3(), ".config", "drafter");
}
function parseFlatToml(text) {
  const result = {};
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line.startsWith("[")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    if (key === "url" || key === "admin_token") result[key] = value;
  }
  return result;
}
function readProfile(profile) {
  const path = join(configDir(), `${profile}.toml`);
  if (!existsSync(path)) return {};
  try {
    return parseFlatToml(readFileSync(path, "utf8"));
  } catch {
    return {};
  }
}
function defaultActor() {
  try {
    return `cli:${userInfo().username}`;
  } catch {
    return "cli";
  }
}
function resolveConfig(options = {}) {
  const profile = options.profile ?? "default";
  const fromFile = readProfile(profile);
  const url = process.env.DRAFTER_URL ?? fromFile.url;
  const adminToken = process.env.DRAFTER_ADMIN_TOKEN ?? fromFile.admin_token;
  if (!url) {
    throw new AxiError("DRAFTER_URL is not set", "USAGE", [
      `Set DRAFTER_URL in the environment, or add url = "..." to ~/.config/drafter/${profile}.toml`
    ]);
  }
  if (!adminToken) {
    throw new AxiError("DRAFTER_ADMIN_TOKEN is not set", "USAGE", [
      `Set DRAFTER_ADMIN_TOKEN in the environment, or add admin_token = "..." to ~/.config/drafter/${profile}.toml`
    ]);
  }
  return { url: url.replace(/\/+$/, ""), adminToken, actor: options.actor ?? defaultActor() };
}
function isConfigured() {
  return Boolean(process.env.DRAFTER_URL) || existsSync(join(configDir(), "default.toml"));
}

// src/cli/commands/common.ts
function clientFrom(parsed) {
  return new DrafterClient(
    resolveConfig({ actor: str(parsed, "--actor"), profile: str(parsed, "--profile") })
  );
}
function wantsJson(parsed) {
  return bool(parsed, "--json");
}
function render(parsed, data, toToon) {
  return wantsJson(parsed) ? renderJson(data) : toToon();
}
async function readFileOrStdin(path) {
  if (path === "-") return readStdin();
  return readFileSync2(path, "utf8");
}
function readStdin() {
  return new Promise((resolve2, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve2(data));
    process.stdin.on("error", reject);
  });
}

// src/cli/commands/docs.ts
var DOCS_FLAGS = {
  create: {
    positionals: 1,
    value: [
      "--title",
      "--owner",
      "--sender-name",
      "--reply-to",
      "--capacities",
      "--public",
      "--show-signatories",
      "--revocation-window-hours",
      "--tags"
    ]
  },
  show: { positionals: 1 },
  open: { positionals: 1, value: ["--comments-close", "--signing-closes"] },
  extend: { positionals: 1, value: ["--comments-close", "--signing-closes"] },
  close: { positionals: 1 },
  reopen: { positionals: 1, value: ["--comments-close", "--signing-closes"] },
  withdraw: { positionals: 1, value: ["--reason"], boolean: ["--public"] }
};
var DOCS_HELP = `usage: drafter-axi docs <create|show|open|extend|close|reopen|withdraw> ...

create <slug> --title <text> --owner <email> --sender-name <text> --reply-to <email>
       [--capacities personal,official] [--public none|read|participate]
       [--show-signatories list|count|none] [--revocation-window-hours <n>] [--tags a,b]
show <slug>
open <slug> --comments-close <iso> --signing-closes <iso>
extend <slug> [--comments-close <iso>] [--signing-closes <iso>]
close <slug>
reopen <slug> [--comments-close <iso>] --signing-closes <iso>
withdraw <slug> --reason <text> [--public]

Every mutation prints the document's key fields and the commit subject.`;
function detailObject(doc) {
  return compact({
    slug: doc.slug,
    title: doc.title,
    state: doc.state,
    phase: doc.phase,
    owner: doc.owner,
    sender_name: doc.sender_name,
    reply_to: doc.reply_to,
    opened_at: doc.opened_at,
    comments_close_at: doc.comments_close_at,
    signing_closes_at: doc.signing_closes_at,
    capacities: doc.capacities,
    public_access: doc.public_access,
    show_signatories: doc.show_signatories,
    tags: doc.tags,
    commit: doc.commit,
    counts: doc.counts
  });
}
async function docsCommand(args) {
  const { sub, parsed } = parseSubcommand("docs", args, DOCS_FLAGS);
  const client = clientFrom(parsed);
  const cli = cliInvocation();
  switch (sub) {
    case "create": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        'drafter-axi docs create <slug> --title "..." --owner <email> --sender-name "..." --reply-to <email>'
      );
      const capacities = csv(str(parsed, "--capacities"));
      const tags = csv(str(parsed, "--tags"));
      const body = {
        slug,
        title: requireStr(parsed, "--title", 'drafter-axi docs create <slug> --title "..." ...'),
        owner: requireStr(parsed, "--owner", "drafter-axi docs create <slug> --owner <email> ..."),
        sender_name: requireStr(
          parsed,
          "--sender-name",
          'drafter-axi docs create <slug> --sender-name "..." ...'
        ),
        reply_to: requireStr(
          parsed,
          "--reply-to",
          "drafter-axi docs create <slug> --reply-to <email> ..."
        ),
        capacities: capacities.length > 0 ? capacities : void 0,
        public_access: str(parsed, "--public"),
        show_signatories: str(parsed, "--show-signatories"),
        revocation_window_hours: str(parsed, "--revocation-window-hours") ? Number(str(parsed, "--revocation-window-hours")) : void 0,
        tags: tags.length > 0 ? tags : void 0
      };
      const doc = await client.post("/documents", body);
      return render(
        parsed,
        doc,
        () => joinBlocks(
          renderObject(detailObject(doc)),
          renderHelp([
            `Run \`${cli} versions publish ${slug} --file <path> --summary "..."\` to publish a first version`
          ])
        )
      );
    }
    case "show": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi docs show <slug>");
      const doc = await client.get(`/documents/${encodeURIComponent(slug)}`);
      return render(
        parsed,
        doc,
        () => joinBlocks(
          renderObject(detailObject(doc)),
          doc.versions.length === 0 ? renderObject({ versions: "no published versions yet" }) : renderList("versions", doc.versions, [
            computed("number", (v) => v.number),
            computed("summary", (v) => v.summary),
            computed("published_at", (v) => v.published_at),
            computed("final", (v) => v.final),
            computed("dispositions", (v) => v.dispositions)
          ]),
          renderHelp([
            doc.versions.length === 0 ? `Run \`${cli} versions publish ${slug} --file <path> --summary "..."\` to publish a first version` : `Run \`${cli} people list ${slug}\` for participation status`
          ])
        )
      );
    }
    case "open": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi docs open <slug> --comments-close <iso> --signing-closes <iso>"
      );
      const doc = await client.post(
        `/documents/${encodeURIComponent(slug)}/open`,
        {
          comments_close_at: requireStr(
            parsed,
            "--comments-close",
            "drafter-axi docs open <slug> --comments-close <iso> --signing-closes <iso>"
          ),
          signing_closes_at: requireStr(
            parsed,
            "--signing-closes",
            "drafter-axi docs open <slug> --comments-close <iso> --signing-closes <iso>"
          )
        }
      );
      return render(
        parsed,
        doc,
        () => joinBlocks(
          renderObject(detailObject(doc)),
          renderHelp([
            `Run \`${cli} people send ${slug}\` if invitees were imported before opening`
          ])
        )
      );
    }
    case "extend": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi docs extend <slug> [--comments-close <iso>] [--signing-closes <iso>]"
      );
      const body = compact({
        comments_close_at: str(parsed, "--comments-close"),
        signing_closes_at: str(parsed, "--signing-closes")
      });
      const doc = await client.post(
        `/documents/${encodeURIComponent(slug)}/schedule`,
        body
      );
      return render(parsed, doc, () => renderObject(detailObject(doc)));
    }
    case "close": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi docs close <slug>");
      const doc = await client.post(
        `/documents/${encodeURIComponent(slug)}/close`
      );
      return render(parsed, doc, () => renderObject(detailObject(doc)));
    }
    case "reopen": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi docs reopen <slug> [--comments-close <iso>] --signing-closes <iso>"
      );
      const body = compact({
        comments_close_at: str(parsed, "--comments-close"),
        signing_closes_at: requireStr(
          parsed,
          "--signing-closes",
          "drafter-axi docs reopen <slug> [--comments-close <iso>] --signing-closes <iso>"
        )
      });
      const doc = await client.post(
        `/documents/${encodeURIComponent(slug)}/reopen`,
        body
      );
      return render(parsed, doc, () => renderObject(detailObject(doc)));
    }
    case "withdraw": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        'drafter-axi docs withdraw <slug> --reason "..." [--public]'
      );
      const body = {
        reason: requireStr(
          parsed,
          "--reason",
          'drafter-axi docs withdraw <slug> --reason "..." [--public]'
        ),
        public: bool(parsed, "--public")
      };
      const doc = await client.post(
        `/documents/${encodeURIComponent(slug)}/withdraw`,
        body
      );
      return render(parsed, doc, () => renderObject(detailObject(doc)));
    }
    default:
      return sub;
  }
}

// src/cli/commands/feedback.ts
import { writeFileSync } from "node:fs";
var FEEDBACK_FLAGS = {
  export: { positionals: 1, value: ["--format", "--out"] }
};
var FEEDBACK_HELP = `usage: drafter-axi feedback export <slug> [--format json|md] [--out <file>]

The LLM-round bundle (\`specs/behaviors/review-and-judgement.md\`): every
pending comment, organized by submission. Feed the json form straight into
your disposition pass, then \`versions publish --dispositions <file.json>\`.`;
async function feedbackCommand(args) {
  const { sub, parsed } = parseSubcommand("feedback", args, FEEDBACK_FLAGS);
  const client = clientFrom(parsed);
  switch (sub) {
    case "export": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi feedback export <slug>");
      const format = str(parsed, "--format", "json");
      if (format !== "json" && format !== "md") {
        throw new AxiError(`"${format}" is not a valid --format`, "USAGE", [
          "Valid formats: json, md"
        ]);
      }
      const out = str(parsed, "--out");
      if (format === "md") {
        const markdown = await client.get(
          `/documents/${encodeURIComponent(slug)}/feedback-export`,
          {
            format: "md"
          }
        );
        if (out) {
          writeFileSync(out, markdown, "utf8");
          return renderObject({ out, format });
        }
        return markdown;
      }
      const bundle = await client.get(
        `/documents/${encodeURIComponent(slug)}/feedback-export`
      );
      const content = JSON.stringify(bundle, null, 2);
      if (out) {
        writeFileSync(out, content, "utf8");
        return renderObject({
          out,
          format,
          pending: bundle.submissions.submitted.length + bundle.submissions.draft.length
        });
      }
      return content;
    }
    default:
      return sub;
  }
}

// src/cli/commands/home.ts
var HOME_FLAGS = { positionals: 0, boolean: ["--if-configured"] };
var DRILL_DOWN_LIMIT = 10;
async function homeCommand(args) {
  const parsed = parseFlags("home", args, HOME_FLAGS);
  const ifConfigured = bool(parsed, "--if-configured");
  const cli = cliInvocation();
  if (!isConfigured()) {
    if (ifConfigured) return "";
    return joinBlocks(
      renderObject({ documents: "DRAFTER_URL is not set" }),
      renderHelp([
        "Set DRAFTER_URL and DRAFTER_ADMIN_TOKEN in the environment (or ~/.config/drafter/default.toml)",
        `Run \`${cli} --help\` to see the full command list`
      ])
    );
  }
  let documents;
  try {
    documents = await clientFrom(parsed).get("/documents");
  } catch (error) {
    if (ifConfigured) {
      const message = error instanceof Error ? error.message : String(error);
      return renderObject({ documents: `could not reach the API: ${message}` });
    }
    throw error;
  }
  if (documents.length === 0) {
    return joinBlocks(
      renderObject({ documents: "0 documents found" }),
      renderHelp([
        `Run \`${cli} docs create <slug> --title "..." --owner <email> ...\` to start one`
      ])
    );
  }
  const client = clientFrom(parsed);
  const openDocs = documents.filter((d) => d.state === "open").sort((a, b) => nextDeadline(a).localeCompare(nextDeadline(b))).slice(0, DRILL_DOWN_LIMIT);
  const drillDowns = /* @__PURE__ */ new Map();
  await Promise.all(
    openDocs.map(async (doc) => {
      try {
        const [invitations, notifications] = await Promise.all([
          client.get(`/documents/${encodeURIComponent(doc.slug)}/invitations`),
          client.get(
            `/documents/${encodeURIComponent(doc.slug)}/notifications`
          )
        ]);
        drillDowns.set(doc.slug, {
          invited: invitations.length,
          opened: invitations.filter((i) => i.opened_at).length,
          signed: invitations.filter((i) => i.signature && !i.signature.revoked).length,
          failed: notifications.failed
        });
      } catch {
      }
    })
  );
  const rows = documents.map((doc) => {
    const drill = drillDowns.get(doc.slug);
    return {
      slug: doc.slug,
      phase: doc.phase,
      next_deadline: nextDeadline(doc) || "",
      invited: drill?.invited ?? doc.counts.participations,
      opened: drill?.opened ?? "",
      signed: drill?.signed ?? doc.counts.signatures.organizations + doc.counts.signatures.individuals + doc.counts.signatures.unlisted,
      failures: drill?.failed ?? ""
    };
  });
  const totalFailures = [...drillDowns.values()].reduce((sum, d) => sum + d.failed, 0);
  const suggestions = [
    `Run \`${cli} docs show <slug>\` for a document's full dashboard`,
    `Run \`${cli} feedback export <slug>\` to pull the pending-comment bundle for an LLM round`
  ];
  if (totalFailures > 0)
    suggestions.unshift(
      `Run \`${cli} notifications retry <slug>\` \u2014 ${totalFailures} failed notification(s) across open documents`
    );
  if (documents.length > DRILL_DOWN_LIMIT + openDocs.length) {
    suggestions.push(
      `Run \`${cli} docs show <slug>\` \u2014 only the ${DRILL_DOWN_LIMIT} nearest-deadline open documents got a full drill-down here`
    );
  }
  return joinBlocks(
    renderList("documents", rows, [
      computed("slug", (r) => r.slug),
      computed("phase", (r) => r.phase),
      computed("next_deadline", (r) => r.next_deadline),
      computed("invited", (r) => r.invited),
      computed("opened", (r) => r.opened),
      computed("signed", (r) => r.signed),
      computed("failures", (r) => r.failures)
    ]),
    renderHelp(suggestions)
  );
}
function nextDeadline(doc) {
  if (doc.phase === "commenting") return doc.comments_close_at ?? "";
  if (doc.phase === "signing") return doc.signing_closes_at ?? "";
  return "";
}

// src/cli/commands/hook.ts
import { execSync } from "node:child_process";
import { existsSync as existsSync2, mkdirSync, readFileSync as readFileSync3, writeFileSync as writeFileSync2 } from "node:fs";
import { homedir as homedir4 } from "node:os";
import { dirname, join as join2, resolve } from "node:path";
import { fileURLToPath as fileURLToPath2 } from "node:url";
var HOOK_FLAGS = {
  install: { positionals: 0, value: ["--scope", "--dir"] },
  uninstall: { positionals: 0, value: ["--scope"] },
  status: { positionals: 0 }
};
var HOOK_HELP = `usage: drafter-axi hook <install|uninstall> [--scope project|global] [--dir <path>]
       drafter-axi hook status

Manage the SessionStart hook that prints the home view (open documents, phase,
next deadline, funnel counts) at the start of every agent session, when
DRAFTER_URL is set (silent otherwise \u2014 a fresh clone without a configured
instance stays quiet).

Default scope is project: written to <repo>/.claude/settings.json (so it is
committed and portable for every contributor). --dir sets the repo root
(default: the git repo root of the current directory). --scope global installs
to ~/.claude/settings.json for every session on this machine instead.`;
var MARKER = "drafter-axi";
var TIMEOUT_SECONDS = 10;
function gitRoot() {
  try {
    const root = execSync("git rev-parse --show-toplevel", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    }).trim();
    return root || void 0;
  } catch {
    return void 0;
  }
}
function projectBase(dirFlag) {
  if (dirFlag) return resolve(dirFlag);
  const root = gitRoot();
  if (root) return root;
  throw new AxiError(
    "couldn't determine the project directory (current directory is not a git repository)",
    "USAGE",
    ["Pass --dir <project-path>, or run from inside the target repo"]
  );
}
function resolveScope(scopeFlag) {
  if (scopeFlag === void 0) return "project";
  if (scopeFlag !== "project" && scopeFlag !== "global") {
    throw new AxiError("--scope must be project or global", "USAGE", [
      "drafter-axi hook install                 (project \u2014 the default)",
      "drafter-axi hook install --scope global"
    ]);
  }
  return scopeFlag;
}
function settingsPath(scope, dirFlag) {
  const base = scope === "global" ? homedir4() : projectBase(dirFlag);
  return join2(base, ".claude", "settings.json");
}
function shimPath() {
  return join2(dirname(fileURLToPath2(import.meta.url)), "drafter-axi");
}
var PROJECT_HOOK_COMMAND = '"${CLAUDE_PROJECT_DIR}/.claude/skills/drafter-axi/scripts/drafter-axi" home --if-configured';
function hookCommand(scope) {
  return scope === "global" ? `${JSON.stringify(shimPath())} home --if-configured` : PROJECT_HOOK_COMMAND;
}
function readSettings(path) {
  if (!existsSync2(path)) return {};
  try {
    const parsed = JSON.parse(readFileSync3(path, "utf8"));
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    throw new AxiError(`could not parse ${path}`, "USAGE", [
      "Fix or remove the malformed JSON file"
    ]);
  }
}
function writeSettings(path, settings) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync2(path, `${JSON.stringify(settings, null, 2)}
`, "utf8");
}
function managedCommand(settings) {
  const groups = settings.hooks?.SessionStart;
  if (!Array.isArray(groups)) return void 0;
  for (const group of groups) {
    for (const hook of group.hooks ?? []) {
      if (typeof hook.command === "string" && hook.command.includes(MARKER)) return hook.command;
    }
  }
  return void 0;
}
function install(args) {
  const parsed = parseFlags("hook install", args, HOOK_FLAGS.install);
  const scope = resolveScope(str(parsed, "--scope"));
  const path = settingsPath(scope, str(parsed, "--dir"));
  const command = hookCommand(scope);
  const settings = readSettings(path);
  const [updated, changed] = computeSessionStartHookUpdate(settings, {
    marker: MARKER,
    command,
    timeoutSeconds: TIMEOUT_SECONDS
  });
  if (changed) writeSettings(path, updated);
  return joinBlocks(
    renderObject({
      hook: changed ? "installed" : "already up to date",
      scope,
      file: path,
      runs: command
    }),
    renderHelp([
      "Every session in this scope opens with the documents dashboard (when DRAFTER_URL is set)",
      `Run \`drafter-axi hook uninstall --scope ${scope}\` to remove it`
    ])
  );
}
function uninstall(args) {
  const parsed = parseFlags("hook uninstall", args, HOOK_FLAGS.uninstall);
  const scope = resolveScope(str(parsed, "--scope"));
  const path = settingsPath(scope, void 0);
  if (!existsSync2(path)) {
    return renderObject({ hook: "not installed (no-op)", scope, file: path });
  }
  const settings = readSettings(path);
  const groups = settings.hooks?.SessionStart;
  let removed = 0;
  if (Array.isArray(groups)) {
    for (const group of groups) {
      const before = group.hooks?.length ?? 0;
      if (group.hooks) {
        group.hooks = group.hooks.filter(
          (h) => !(typeof h.command === "string" && h.command.includes(MARKER))
        );
      }
      removed += before - (group.hooks?.length ?? 0);
    }
    settings.hooks.SessionStart = groups.filter((g) => (g.hooks?.length ?? 0) > 0);
  }
  if (removed > 0) writeSettings(path, settings);
  return renderObject({
    hook: removed > 0 ? "removed" : "not installed (no-op)",
    scope,
    file: path
  });
}
function status() {
  const describe = (path) => {
    const command = existsSync2(path) ? managedCommand(readSettings(path)) : void 0;
    return command ? { installed: true, runs: command } : { installed: false };
  };
  const globalPath = join2(homedir4(), ".claude", "settings.json");
  const rows = [
    { scope: "global", file: globalPath, ...describe(globalPath) }
  ];
  const root = gitRoot();
  if (root) {
    const projectPath = join2(root, ".claude", "settings.json");
    rows.push({ scope: "project", file: projectPath, ...describe(projectPath) });
  } else {
    rows.push({
      scope: "project",
      file: "(cwd is not a git repo \u2014 pass --dir to `hook install`)",
      installed: "n/a"
    });
  }
  return joinBlocks(
    renderList("hooks", rows, [
      { name: "scope", extract: (r) => r.scope },
      { name: "installed", extract: (r) => r.installed },
      { name: "file", extract: (r) => r.file }
    ]),
    renderHelp(["Run `drafter-axi hook install` to load the documents dashboard each session"])
  );
}
async function hookCommand_(args) {
  const verb = args[0];
  const rest = args.slice(1);
  switch (verb) {
    case "install":
      return install(rest);
    case "uninstall":
      return uninstall(rest);
    case "status":
      return status();
    default:
      throw new AxiError(`unknown hook subcommand: ${verb ?? "(none)"}`, "USAGE", [
        "Use: hook install [--scope] [--dir] | hook uninstall [--scope] | hook status"
      ]);
  }
}

// src/cli/commands/instance.ts
var INIT_DATA_REPO_FLAGS = { positionals: 0 };
var INIT_DATA_REPO_HELP = `usage: drafter-axi init-data-repo

First-boot helper: writes the four sheet configs into an empty data repo.
Refuses if sheets already exist.`;
async function initDataRepoCommand(args) {
  const parsed = parseFlags("init-data-repo", args, INIT_DATA_REPO_FLAGS);
  const client = clientFrom(parsed);
  const result = await client.post("/init-data-repo");
  return render(parsed, result, () => renderObject(result));
}

// src/cli/commands/notifications.ts
var NOTIFICATIONS_FLAGS = {
  list: { positionals: 1 },
  retry: { positionals: 1, value: ["--event", "--person"] }
};
var NOTIFICATIONS_HELP = `usage: drafter-axi notifications <list|retry> ...

list <slug>
retry <slug> [--event <name>] [--person <id>]`;
async function notificationsCommand(args) {
  const { sub, parsed } = parseSubcommand("notifications", args, NOTIFICATIONS_FLAGS);
  const client = clientFrom(parsed);
  switch (sub) {
    case "list": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi notifications list <slug>");
      const summary = await client.get(
        `/documents/${encodeURIComponent(slug)}/notifications`
      );
      return render(
        parsed,
        summary,
        () => joinBlocks(
          renderObject({ sent: summary.sent, pending: summary.pending, failed: summary.failed }),
          summary.failed > 0 ? renderHelp([`Run \`drafter-axi notifications retry ${slug}\` to re-dispatch`]) : ""
        )
      );
    }
    case "retry": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi notifications retry <slug>");
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/notifications/retry`,
        {
          event: str(parsed, "--event"),
          person: str(parsed, "--person")
        }
      );
      return render(parsed, result, () => renderObject(result));
    }
    default:
      return sub;
  }
}

// src/cli/commands/people.ts
import { writeFileSync as writeFileSync3 } from "node:fs";
var PEOPLE_FLAGS = {
  import: { positionals: 2, value: ["--suggested-capacity"] },
  list: { positionals: 1, value: ["--status", "--source", "-q"], boolean: ["--contacts"] },
  links: { positionals: 1, value: ["--person", "--out"] },
  send: { positionals: 1, value: ["--person"], boolean: ["--only-unsent"] },
  remind: { positionals: 1, value: ["--target"], boolean: ["--dry-run"] },
  "revoke-link": { positionals: 2 },
  "reissue-link": { positionals: 2 }
};
var PEOPLE_HELP = `usage: drafter-axi people <import|list|links|send|remind|revoke-link|reissue-link> ...

import <slug> [<file.ndjson>|-] [--suggested-capacity personal|official]
       Reads NDJSON or a JSON array (defaults to stdin when the file is omitted);
       a gitsheets people sheet's NDJSON export works directly.
list <slug> [--status <status>] [--source <source>] [-q <text>] [--contacts]
       Never prints tokens; emails only with --contacts.
links <slug> [--person a,b] [--out <file.csv>]
       The only command that returns tokens \u2014 recorded as an admin event.
send <slug> [--only-unsent] [--person a,b]
remind <slug> --target unopened|opened-not-acted [--dry-run]
revoke-link <slug> <person>
reissue-link <slug> <person>
       Prints the new link once.`;
function parseImportRows(text) {
  const trimmed = text.trim();
  if (trimmed.length === 0) {
    throw new AxiError("no rows to import (input was empty)", "USAGE", [
      "Pass a file path, or pipe NDJSON/a JSON array to stdin with `-`"
    ]);
  }
  if (trimmed.startsWith("[")) {
    const parsed = JSON.parse(trimmed);
    if (!Array.isArray(parsed)) {
      throw new AxiError("import input must be a JSON array or NDJSON", "USAGE", []);
    }
    return parsed;
  }
  return trimmed.split("\n").map((line) => line.trim()).filter((line) => line.length > 0).map((line) => JSON.parse(line));
}
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i += 1;
        } else {
          inQuotes = false;
        }
      } else {
        field += c;
      }
      continue;
    }
    if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\r") {
    } else if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows.filter((r) => !(r.length === 1 && r[0] === ""));
}
async function peopleCommand(args) {
  const { sub, parsed } = parseSubcommand("people", args, PEOPLE_FLAGS);
  const client = clientFrom(parsed);
  switch (sub) {
    case "import": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi people import <slug> [<file.ndjson>|-]"
      );
      const filePath = parsed.positional[1] ?? "-";
      const suggestedCapacity = str(parsed, "--suggested-capacity");
      const rows = parseImportRows(await readFileOrStdin(filePath));
      if (suggestedCapacity) {
        for (const row of rows) {
          if (row.suggested_capacity === void 0) row.suggested_capacity = suggestedCapacity;
        }
      }
      const ndjson = rows.map((row) => JSON.stringify(row)).join("\n");
      const result = await client.postText(
        `/documents/${encodeURIComponent(slug)}/invitations/import`,
        ndjson,
        "application/x-ndjson"
      );
      return render(
        parsed,
        result,
        () => joinBlocks(
          renderObject(result),
          renderHelp([`Run \`drafter-axi people list ${slug}\` to see the imported invitees`])
        )
      );
    }
    case "list": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi people list <slug>");
      const contacts = bool(parsed, "--contacts");
      const rows = await client.get(
        `/documents/${encodeURIComponent(slug)}/invitations`,
        {
          status: str(parsed, "--status"),
          source: str(parsed, "--source"),
          q: str(parsed, "-q")
        }
      );
      const schema = [
        computed("person", (r) => r.person),
        computed("name", (r) => r.name),
        ...contacts ? [computed("email", (r) => r.email)] : [],
        computed("status", (r) => r.status),
        computed("opens", (r) => r.opens),
        computed("sent_at", (r) => r.sent_at ?? "")
      ];
      return render(
        parsed,
        contacts ? rows : rows.map(({ email: _email, ...rest }) => rest),
        () => joinBlocks(
          rows.length === 0 ? renderObject({ people: "0 invitees found" }) : renderList("people", rows, schema),
          renderHelp(contacts ? [] : [`Pass --contacts to include email addresses (never tokens)`])
        )
      );
    }
    case "links": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi people links <slug>");
      const person = csv(str(parsed, "--person"));
      const csvText = await client.post(
        `/documents/${encodeURIComponent(slug)}/invitations/links`,
        {
          person: person.length > 0 ? person : void 0
        }
      );
      const out = str(parsed, "--out");
      if (out) {
        writeFileSync3(out, csvText, "utf8");
        const rowCount = Math.max(0, parseCsv(csvText).length - 1);
        return render(parsed, { out, rows: rowCount }, () => renderObject({ out, rows: rowCount }));
      }
      const parsedRows = parseCsv(csvText);
      const [header, ...dataRows] = parsedRows;
      const rows = dataRows.map(
        (r) => Object.fromEntries((header ?? []).map((h, i) => [h, r[i] ?? ""]))
      );
      return render(
        parsed,
        rows,
        () => joinBlocks(
          rows.length === 0 ? renderObject({ links: "0 links found" }) : renderList("links", rows, [
            computed("person", (r) => r.person),
            computed("name", (r) => r.name),
            computed("email", (r) => r.email),
            computed("link", (r) => r.link)
          ]),
          renderHelp(["Links are tokens \u2014 handle this output like a credential"])
        )
      );
    }
    case "send": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi people send <slug>");
      const person = csv(str(parsed, "--person"));
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/invitations/send`,
        {
          only_unsent: bool(parsed, "--only-unsent") || void 0,
          person: person.length > 0 ? person : void 0
        }
      );
      return render(
        parsed,
        result,
        () => renderObject({
          queued: result.queued,
          mailer_export: result.csv ? "included (rerun with --json to capture)" : void 0
        })
      );
    }
    case "remind": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi people remind <slug> --target unopened|opened-not-acted"
      );
      const targetFlag = requireStr(
        parsed,
        "--target",
        "drafter-axi people remind <slug> --target unopened|opened-not-acted"
      );
      const target = targetFlag === "opened-not-acted" ? "opened_not_acted" : targetFlag;
      if (target !== "unopened" && target !== "opened_not_acted") {
        throw new AxiError(`"${targetFlag}" is not a valid --target`, "USAGE", [
          "Valid targets: unopened, opened-not-acted"
        ]);
      }
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/invitations/remind`,
        {
          target,
          dry_run: bool(parsed, "--dry-run") || void 0
        }
      );
      return render(parsed, result, () => renderObject(result));
    }
    case "revoke-link": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi people revoke-link <slug> <person>"
      );
      const person = requirePositional(
        parsed,
        1,
        "person",
        "drafter-axi people revoke-link <slug> <person>"
      );
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/invitations/${encodeURIComponent(person)}/revoke-link`
      );
      return render(parsed, result, () => renderObject(result));
    }
    case "reissue-link": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi people reissue-link <slug> <person>"
      );
      const person = requirePositional(
        parsed,
        1,
        "person",
        "drafter-axi people reissue-link <slug> <person>"
      );
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/invitations/${encodeURIComponent(person)}/reissue-link`
      );
      return render(
        parsed,
        result,
        () => joinBlocks(
          renderObject(result),
          renderHelp([
            "This link is shown once \u2014 it is not retrievable again except via `people links`"
          ])
        )
      );
    }
    default:
      return sub;
  }
}

// src/cli/commands/signatures.ts
var SIGNATURES_FLAGS = {
  list: { positionals: 1, boolean: ["--include-revoked", "--conditional"] },
  revoke: { positionals: 2, value: ["--reason"] }
};
var SIGNATURES_HELP = `usage: drafter-axi signatures <list|revoke> ...

list <slug> [--include-revoked] [--conditional]
revoke <slug> <person> --reason "<text>"
       Admin revocation; a confirmation email goes to the person.`;
async function signaturesCommand(args) {
  const { sub, parsed } = parseSubcommand("signatures", args, SIGNATURES_FLAGS);
  const client = clientFrom(parsed);
  switch (sub) {
    case "list": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi signatures list <slug>");
      const includeRevoked = bool(parsed, "--include-revoked");
      const conditionalOnly = bool(parsed, "--conditional");
      let rows = await client.get(
        `/documents/${encodeURIComponent(slug)}/signatures`,
        {
          include_revoked: includeRevoked ? "true" : void 0
        }
      );
      if (conditionalOnly) rows = rows.filter((r) => r.signature?.conditional === true);
      return render(
        parsed,
        rows,
        () => joinBlocks(
          rows.length === 0 ? renderObject({ signatures: "0 signatures found" }) : renderList("signatures", rows, [
            computed("person", (r) => r.person),
            computed("name", (r) => r.name),
            computed("capacity", (r) => r.signature?.capacity ?? ""),
            computed("conditional", (r) => r.signature?.conditional ?? false),
            computed("revoked", (r) => r.signature?.revoked ?? false),
            computed("signed_at", (r) => r.signature?.signed_at ?? "")
          ])
        )
      );
    }
    case "revoke": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        'drafter-axi signatures revoke <slug> <person> --reason "..."'
      );
      const person = requirePositional(
        parsed,
        1,
        "person",
        'drafter-axi signatures revoke <slug> <person> --reason "..."'
      );
      const reason = requireStr(
        parsed,
        "--reason",
        'drafter-axi signatures revoke <slug> <person> --reason "..."'
      );
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/signatures/${encodeURIComponent(person)}/revoke`,
        { reason }
      );
      return render(
        parsed,
        result,
        () => joinBlocks(
          renderObject(result),
          renderHelp([`Run \`drafter-axi signatures list ${slug}\` to confirm`])
        )
      );
    }
    default:
      return sub;
  }
}

// src/cli/commands/submissions.ts
var SUBMISSIONS_FLAGS = {
  list: {
    positionals: 1,
    value: ["--version", "--person"],
    boolean: ["--pending", "--include-drafts"]
  }
};
var SUBMISSIONS_HELP = `usage: drafter-axi submissions list <slug> [--pending] [--version <n>] [--person <id>] [--include-drafts]

Whole submissions, each with its comments (shown as two tables: submissions,
then comments). Drafts come only with --include-drafts, and every draft row
carries state: draft so it can't be mistaken for a submitted answer.`;
async function submissionsCommand(args) {
  const { sub, parsed } = parseSubcommand("submissions", args, SUBMISSIONS_FLAGS);
  const client = clientFrom(parsed);
  switch (sub) {
    case "list": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi submissions list <slug>");
      const includeDrafts = bool(parsed, "--include-drafts");
      const submissions = await client.get(
        `/documents/${encodeURIComponent(slug)}/submissions`,
        {
          state: includeDrafts ? "all" : "submitted",
          disposition: bool(parsed, "--pending") ? "pending" : void 0,
          version: str(parsed, "--version"),
          person: str(parsed, "--person")
        }
      );
      const comments = submissions.flatMap(
        (s) => s.comments.map((c) => ({
          submission: s.id,
          comment: c.id,
          anchor: c.anchor ? JSON.stringify(c.anchor) : "",
          body: c.body,
          disposition: c.disposition?.outcome ?? "pending"
        }))
      );
      return render(
        parsed,
        submissions,
        () => joinBlocks(
          submissions.length === 0 ? renderObject({ submissions: "0 submissions found" }) : renderList("submissions", submissions, [
            computed("id", (s) => s.id),
            computed("author", (s) => s.author),
            computed("version", (s) => s.version),
            computed("state", (s) => s.state),
            computed("judgement", (s) => s.judgement ?? ""),
            computed("comments", (s) => s.comments.length),
            computed("pending", (s) => s.comments.filter((c) => !c.disposition).length)
          ]),
          comments.length === 0 ? "" : renderList("comments", comments, [
            computed("submission", (c) => c.submission),
            computed("comment", (c) => c.comment),
            computed("body", (c) => truncate(String(c.body))),
            computed("disposition", (c) => c.disposition)
          ]),
          renderHelp([`Run \`drafter-axi feedback export ${slug}\` for the full LLM-round bundle`])
        )
      );
    }
    default:
      return sub;
  }
}
function truncate(text, max = 300) {
  return text.length > max ? `${text.slice(0, max - 1)}\u2026` : text;
}

// src/cli/commands/versions.ts
var VERSIONS_FLAGS = {
  list: { positionals: 1 },
  show: { positionals: 2, boolean: ["--body"] },
  publish: {
    positionals: 1,
    value: ["--file", "--summary", "--notes-file", "--dispositions"],
    boolean: ["--final"]
  },
  compare: { positionals: 3, boolean: ["--unchanged"] }
};
var VERSIONS_HELP = `usage: drafter-axi versions <list|show|publish|compare> ...

list <slug>
show <slug> <n> [--body]
publish <slug> --file <path> --summary "<text>" [--notes-file <path>] [--final] [--dispositions <file.json>]
compare <slug> <from> <to> [--unchanged]

publish is one commit: the document body, disposition fields on any submissions
named in --dispositions (a JSON array of {submission, comment, outcome, note?}),
and a signing_closes_at extension if the document is mid-signing. Prints the
version number, the commit subject, and notification counts.`;
var BODY_PREVIEW_CHARS = 800;
function toTerminalText(html) {
  return html.replace(/<ins>/g, "{+").replace(/<\/ins>/g, "+}").replace(/<del>/g, "{-").replace(/<\/del>/g, "-}").replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
}
function parseDispositions(text) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (error) {
    throw new AxiError(
      `--dispositions file is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
      "USAGE",
      ["The file must be a JSON array of {submission, comment, outcome, note?}"]
    );
  }
  if (!Array.isArray(parsed)) {
    throw new AxiError("--dispositions file must contain a JSON array", "USAGE", [
      "The file must be a JSON array of {submission, comment, outcome, note?}"
    ]);
  }
  return parsed;
}
async function versionsCommand(args) {
  const { sub, parsed } = parseSubcommand("versions", args, VERSIONS_FLAGS);
  const client = clientFrom(parsed);
  switch (sub) {
    case "list": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi versions list <slug>");
      const versions = await client.get(
        `/documents/${encodeURIComponent(slug)}/versions`
      );
      return render(
        parsed,
        versions,
        () => versions.length === 0 ? renderObject({ versions: "no published versions yet" }) : renderList("versions", versions, [
          computed("number", (v) => v.number),
          computed("summary", (v) => v.summary),
          computed("published_at", (v) => v.published_at),
          computed("final", (v) => v.final),
          computed("dispositions", (v) => v.dispositions)
        ])
      );
    }
    case "show": {
      const slug = requirePositional(parsed, 0, "slug", "drafter-axi versions show <slug> <n>");
      const n = requirePositional(parsed, 1, "n", "drafter-axi versions show <slug> <n>");
      const version = await client.get(
        `/documents/${encodeURIComponent(slug)}/versions/${encodeURIComponent(n)}`
      );
      const showBody = bool(parsed, "--body");
      const bodyBlock = showBody ? renderObject({ body: version.body }) : renderObject({
        body: version.body.length > BODY_PREVIEW_CHARS ? `${version.body.slice(0, BODY_PREVIEW_CHARS)}
... (truncated, ${version.body.length} chars total)` : version.body
      });
      return render(
        parsed,
        version,
        () => joinBlocks(
          renderObject({
            number: version.number,
            commit: version.commit,
            summary: version.summary,
            published_at: version.published_at,
            published_by: version.published_by,
            final: version.final,
            notes: version.notes
          }),
          bodyBlock,
          version.dispositions.length > 0 ? renderList("dispositions", version.dispositions, [
            computed("submission", (d) => d.submission),
            computed("comment", (d) => d.comment),
            computed("outcome", (d) => d.outcome),
            computed("note", (d) => d.note ?? "")
          ]) : "",
          !showBody && version.body.length > BODY_PREVIEW_CHARS ? renderHelp([
            `Run \`drafter-axi versions show ${slug} ${n} --body\` for the full body`
          ]) : ""
        )
      );
    }
    case "publish": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        'drafter-axi versions publish <slug> --file <path> --summary "..."'
      );
      const filePath = requireStr(
        parsed,
        "--file",
        'drafter-axi versions publish <slug> --file <path> --summary "..."'
      );
      const summary = requireStr(
        parsed,
        "--summary",
        'drafter-axi versions publish <slug> --file <path> --summary "..."'
      );
      const body = await readFileOrStdin(filePath);
      const notesFile = str(parsed, "--notes-file");
      const notes = notesFile ? await readFileOrStdin(notesFile) : void 0;
      const dispositionsFile = str(parsed, "--dispositions");
      const dispositions = dispositionsFile ? parseDispositions(await readFileOrStdin(dispositionsFile)) : void 0;
      const result = await client.post(
        `/documents/${encodeURIComponent(slug)}/versions`,
        {
          body,
          summary,
          notes,
          final: bool(parsed, "--final") || void 0,
          dispositions
        }
      );
      return render(
        parsed,
        result,
        () => joinBlocks(
          renderObject({
            number: result.number,
            summary: result.summary,
            commit: result.commit,
            signing_closes_at: result.signing_closes_at
          }),
          renderObject({ notified: result.notified }),
          renderHelp([`Run \`drafter-axi docs show ${slug}\` to see the updated dashboard`])
        )
      );
    }
    case "compare": {
      const slug = requirePositional(
        parsed,
        0,
        "slug",
        "drafter-axi versions compare <slug> <from> <to>"
      );
      const from = requirePositional(
        parsed,
        1,
        "from",
        "drafter-axi versions compare <slug> <from> <to>"
      );
      const to = requirePositional(
        parsed,
        2,
        "to",
        "drafter-axi versions compare <slug> <from> <to>"
      );
      const result = await client.get(
        `/documents/${encodeURIComponent(slug)}/compare`,
        {
          from,
          to
        }
      );
      const includeUnchanged = bool(parsed, "--unchanged");
      const blocks = result.blocks.filter((b) => includeUnchanged || b.status !== "same");
      return render(
        parsed,
        result,
        () => joinBlocks(
          renderObject({ from: result.from, to: result.to, summary: result.summary }),
          blocks.length === 0 ? renderObject({ blocks: "no changed blocks" }) : renderList("blocks", blocks, [
            computed("status", (b) => b.status),
            computed("id", (b) => b.id),
            computed("text", (b) => toTerminalText(b.html))
          ]),
          renderHelp(
            includeUnchanged ? [] : [
              `Run \`drafter-axi versions compare ${slug} ${from} ${to} --unchanged\` to include unchanged blocks`
            ]
          )
        )
      );
    }
    default:
      return sub;
  }
}

// src/cli/reference.ts
var DESCRIPTION = "Drive a community-drafter document from the shell \u2014 create, open, publish revisions, invite and track signers, and export feedback bundles for an LLM round.";
var COMMAND_GROUPS = [
  {
    group: "Documents",
    commands: [
      {
        usage: 'docs create <slug> --title "<text>" --owner <email> --sender-name "<text>" --reply-to <email> [--capacities personal,official] [--public none|read|participate] [--show-signatories list|count|none] [--revocation-window-hours <n>] [--tags a,b]',
        summary: "Create a document in draft."
      },
      { usage: "docs show <slug>", summary: "Dashboard numbers, versions, and schedule." },
      {
        usage: "docs open <slug> --comments-close <iso> --signing-closes <iso>",
        summary: "Open commenting and signing, and send invitations."
      },
      {
        usage: "docs extend <slug> [--comments-close <iso>] [--signing-closes <iso>]",
        summary: "Push a deadline later (never earlier)."
      },
      { usage: "docs close <slug>", summary: "Close signing now." },
      {
        usage: "docs reopen <slug> [--comments-close <iso>] --signing-closes <iso>",
        summary: "Reopen a closed document."
      },
      {
        usage: 'docs withdraw <slug> --reason "<text>" [--public]',
        summary: "Withdraw the document."
      }
    ]
  },
  {
    group: "Versions",
    commands: [
      { usage: "versions list <slug>", summary: "Every published version, newest last." },
      { usage: "versions show <slug> <n> [--body]", summary: "One version, with dispositions." },
      {
        usage: 'versions publish <slug> --file <path> --summary "<text>" [--notes-file <path>] [--final] [--dispositions <file.json>]',
        summary: "Publish a new version in one commit; prints the version number, commit subject, and notification counts."
      },
      {
        usage: "versions compare <slug> <from> <to> [--unchanged]",
        summary: "A text redline between two versions."
      }
    ]
  },
  {
    group: "People",
    commands: [
      {
        usage: "people import <slug> [<file.ndjson>|-] [--suggested-capacity personal|official]",
        summary: "Import invitees from NDJSON or a JSON array (a gitsheets people export works directly)."
      },
      {
        usage: "people list <slug> [--status <status>] [--source <source>] [-q <text>] [--contacts]",
        summary: "Participation statuses \u2014 never tokens; emails only with --contacts."
      },
      {
        usage: "people links <slug> [--person a,b] [--out <file.csv>]",
        summary: "Export personal sign-in links (recorded)."
      },
      {
        usage: "people send <slug> [--only-unsent] [--person a,b]",
        summary: "Send invitations."
      },
      {
        usage: "people remind <slug> --target unopened|opened-not-acted [--dry-run]",
        summary: "Send reminders to a target segment."
      },
      { usage: "people revoke-link <slug> <person>", summary: "Revoke one person's link." },
      {
        usage: "people reissue-link <slug> <person>",
        summary: "Reissue one person's link (prints it once)."
      }
    ]
  },
  {
    group: "Signatures",
    commands: [
      {
        usage: "signatures list <slug> [--include-revoked] [--conditional]",
        summary: "Every signature, with sign/revoke dates."
      },
      {
        usage: 'signatures revoke <slug> <person> --reason "<text>"',
        summary: "Admin revocation of a signature."
      }
    ]
  },
  {
    group: "Submissions and feedback",
    commands: [
      {
        usage: "submissions list <slug> [--pending] [--version <n>] [--person <id>] [--include-drafts]",
        summary: "Whole submissions with their comments; drafts only on request, and always labeled."
      },
      {
        usage: "feedback export <slug> [--format json|md] [--out <file>]",
        summary: "The LLM-round bundle \u2014 pipe straight into `versions publish --dispositions`."
      }
    ]
  },
  {
    group: "Notifications",
    commands: [
      { usage: "notifications list <slug>", summary: "Sent, pending, and failed counts." },
      {
        usage: "notifications retry <slug> [--event <name>] [--person <id>]",
        summary: "Re-dispatch anything not yet notified."
      }
    ]
  },
  {
    group: "Instance",
    commands: [
      {
        usage: "init-data-repo",
        summary: "First-boot helper: write sheet configs into an empty data repo."
      }
    ]
  },
  {
    group: "Session",
    commands: [
      {
        usage: "hook install [--scope project|global] [--dir <path>] | hook status | hook uninstall [--scope project|global]",
        summary: "Manage the SessionStart hook that prints the home view (documents, deadlines, funnel counts) at the start of every agent session."
      }
    ]
  }
];
function commandDoc(name) {
  for (const group of COMMAND_GROUPS) {
    for (const doc of group.commands) {
      const first = doc.usage.split(" ")[0];
      if (first === name) return doc;
    }
  }
  return void 0;
}
function renderCommandHelp(name) {
  const doc = commandDoc(name);
  if (!doc) return null;
  const lines = [
    `usage: drafter-axi ${doc.usage}`,
    "",
    doc.summary,
    "",
    "`--actor <label>` sets X-Actor (default cli:<os user>); `--json` prints raw JSON instead of TOON."
  ];
  return `${lines.join("\n")}
`;
}
function renderTopLevelHelp() {
  const lines = [`drafter-axi \u2014 ${DESCRIPTION}`, "", "usage: drafter-axi <command> [args] [flags]"];
  for (const group of COMMAND_GROUPS) {
    lines.push("", `${group.group}:`);
    for (const doc of group.commands) {
      lines.push(`  ${doc.usage}`);
      lines.push(`      ${doc.summary}`);
    }
  }
  lines.push(
    "",
    "Config: DRAFTER_URL / DRAFTER_ADMIN_TOKEN in the environment (or ~/.config/drafter/<profile>.toml).",
    "`--actor <label>` sets X-Actor on any command; `--json` prints raw JSON instead of TOON.",
    "Run `drafter-axi <command> --help` for usage on any command.",
    "Run `drafter-axi` with no arguments to see every open document's status."
  );
  return lines.join("\n");
}

// src/cli/cli.ts
var VERSION = true ? "daeecc1" : "dev";
var COMMAND_HELP = {
  docs: DOCS_HELP,
  versions: VERSIONS_HELP,
  people: PEOPLE_HELP,
  signatures: SIGNATURES_HELP,
  submissions: SUBMISSIONS_HELP,
  feedback: FEEDBACK_HELP,
  notifications: NOTIFICATIONS_HELP,
  "init-data-repo": INIT_DATA_REPO_HELP,
  hook: HOOK_HELP
};
var COMMANDS = {
  // Registered under its own name (in addition to the required zero-arg
  // `home`) so the SessionStart hook can invoke `home --if-configured` —
  // the SDK rejects a leading flag before a command, so the bare zero-arg
  // form can never itself accept a flag (axi-skills § gotchas).
  home: homeCommand,
  docs: docsCommand,
  versions: versionsCommand,
  people: peopleCommand,
  signatures: signaturesCommand,
  submissions: submissionsCommand,
  feedback: feedbackCommand,
  notifications: notificationsCommand,
  "init-data-repo": initDataRepoCommand,
  hook: hookCommand_
};
function formatError(error) {
  if (error instanceof AxiError) {
    const details = error.details;
    const head = { error: error.message, code: error.code };
    if (details && Object.keys(details).length > 0) head.details = details;
    return {
      output: `${joinBlocks(renderObject(head), renderHelp(error.suggestions))}
`,
      exitCode: exitCodeForCode(error.code)
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return {
    output: `${renderObject({ error: `unexpected failure: ${message}`, code: "INTERNAL_ERROR" })}
`,
    exitCode: 1
  };
}
async function main(options = {}) {
  await runAxiCli({
    description: DESCRIPTION,
    version: VERSION,
    ...options.argv ? { argv: options.argv } : {},
    ...options.stdout ? { stdout: options.stdout } : {},
    topLevelHelp: renderTopLevelHelp(),
    getCommandHelp: (command) => COMMAND_HELP[command] ?? renderCommandHelp(command),
    home: async () => homeCommand([]),
    commands: COMMANDS,
    formatError
    // Hooks are managed explicitly via the `hook` command. The SDK's
    // auto-install is a no-op for a `.mjs`-named bundle anyway (it only
    // infers from `dist/bin/<name>.js` or an extension-less binary).
  });
}

// src/cli/bin.ts
await main();
